name: Build Atlases
on:
  push:
    paths:
      - 'atlases_src/**'
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0


      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Pillow
        run: python -m pip install --upgrade pip && pip install Pillow

      - name: Build atlases
        run: |
          python tools/build_atlases.py

      - name: Commit and push changes (if any)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add atlases || true
          if git diff --cached --quiet; then
            echo "No atlas changes to commit."
          else
            git commit -m "Auto-build atlases [ci]" || true
            git pull --rebase origin main
            git push
          fi
